# Generated by Django 3.2 on 2021-04-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20210402_0111"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phone",
            name="email",
        ),
        migrations.AddField(
            model_name="phone",
            name="person",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="phones", to="app.person"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="phone",
            name="phone_number",
            field=models.BigIntegerField(),
        ),
    ]
