# Generated by Django 3.2 on 2021-04-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20210414_0045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
