# Generated by Django 3.2 on 2021-04-10 18:44

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20210410_0042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="nickname",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w]+\\Z"),
                        "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
