# Generated by Django 3.2 on 2021-04-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_offer_description'),
        ('app', '0006_alter_person_nickname'),
    ]

    operations = [
    ]
