# Generated by Django 3.2 on 2021-05-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_person_managers"),
        ("app", "0008_rename_plataform_offer_platform"),
    ]

    operations = []
