# Generated by Django 3.2 on 2021-05-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20210501_1902'),
        ('app', '0009_merge_20210502_1608'),
        ('app', '0009_merge_20210502_1740'),
    ]

    operations = [
    ]
